"use client"

import { createContext, useContext, useState, ReactNode } from "react"

type Language = "en" | "sk"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    "nav.services": "Services",
    "nav.caseStudies": "Case Studies",
    "nav.about": "About",
    "nav.testimonials": "Testimonials",
    "nav.faq": "FAQ",
    "nav.bookStrategy": "Free Consultation",
    "hero.trusted": "Trusted by European e-commerce brands",
    "hero.headline1": "Help your e-shop ",
    "hero.headline2": "sell more",
    "hero.headline3": " with ",
    "hero.headline4": "AI-powered content",
    "hero.headline5": " and ",
    "hero.headline6": "Meta advertising",
    "hero.subheadline": "We'll build a custom strategy, save you weeks on content creation, and manage everything from strategy to execution.",
    "hero.cta": "Book Free Consultation",
    "hero.stat1.value": "€1.4M+",
    "hero.stat1.label": "Revenue Generated",
    "hero.stat2.value": "10,500+",
    "hero.stat2.label": "Orders Generated",
    "hero.stat3.value": "20+",
    "hero.stat3.label": "Brands Scaled",
    "hero.stat4.value": "12+",
    "hero.stat4.label": "Years of Team Experience",
    "hero.viewCaseStudies": "See Results",
    "hero.microcopy": "15-minute discovery call. Tailored strategy. Built for your brand.",
    "services.label": "What We Do",
    "services.title1": "Everything your e-shop needs to ",
    "services.title2": "scale in 2026",
    "services.description": "Advertising is just one piece. We build the complete system—strategy, creative, and conversion funnel. Every component works in harmony.",
    "services.meta.title": "Meta Ads",
    "services.meta.description": "Facebook and Instagram campaigns designed to convert. We don't just drive clicks—we drive orders. Full-funnel approach from awareness to purchase.",
    "services.google.title": "Google Ads",
    "services.google.description": "Search, Shopping, and Performance Max campaigns that capture high-intent customers actively searching for your products.",
    "services.tiktok.title": "TikTok Ads",
    "services.tiktok.description": "Reach and engage younger audiences with compelling video content. Comprehensive campaign management and creative strategy.",
    "services.creative.title": "Creative & Content",
    "services.creative.description": "Ads that stop scrolls. User-generated content videos, graphics, landing pages—we create everything you need.",
    "whyUs.label": "Why Choose Us",
    "whyUs.title1": "We work differently",
    "whyUs.description": "We bring real experience from our own projects and from scaling our clients' brands. We know what works, what doesn't, and we're constantly testing and improving.",
    "whyUs.point1.title": "We're passionate",
    "whyUs.point1.description": "We genuinely love this work. We care about delivering excellence and constantly seeking better ways to achieve results.",
    "whyUs.point2.title": "We think holistically",
    "whyUs.point2.description": "We don't just optimize ads in isolation. We analyze your entire system—website, offer, messaging—ensuring everything works together seamlessly.",
    "whyUs.point3.title": "We save your time",
    "whyUs.point3.description": "Strategy, creative development, execution, optimization—we handle it all so you can focus on running your business.",
    "whyUs.point4.title": "We deliver results",
    "whyUs.point4.description": "We focus on metrics that matter: sales, revenue, and sustainable growth—not vanity metrics.",
    "howItWorks.label": "How It Works",
    "howItWorks.title1": "We grow your brand through our ",
    "howItWorks.title2": "90-day sprint",
    "howItWorks.step1.title": "Analysis",
    "howItWorks.step1.description": "We audit your marketing, analyze competitors, and identify growth opportunities. Together we develop a strategic roadmap.",
    "howItWorks.step2.title": "Strategy & Creative",
    "howItWorks.step2.description": "We create your advertising strategy, develop creative assets, and implement comprehensive tracking infrastructure.",
    "howItWorks.step3.title": "Launch & Optimize",
    "howItWorks.step3.description": "Your campaigns go live. We monitor daily performance and continuously optimize for maximum return on ad spend.",
    "howItWorks.step4.title": "Scale",
    "howItWorks.step4.description": "Once we identify winning combinations, we scale strategically and profitably.",
    "howItWorks.cta": "Get Started",
    "howItWorks.note": "Initial partnership: 90 days. Then long-term collaboration built on proven results.",
    "caseStudies.label": "Results",
    "caseStudies.title1": "Real numbers,",
    "caseStudies.title2": " real brands",
    "caseStudies.description": "See how we've helped e-commerce brands grow through strategic paid advertising.",
    "testimonials.quote": "\"You can see the effort and genuine care you put into this work. That matters. This is the best approach to advertising I've experienced.\"",
    "whoItsFor.label": "Who We Work With",
    "whoItsFor.title1": "We're not ",
    "whoItsFor.title2": "for everyone",
    "whoItsFor.description": "We partner with brands committed to investing in growth and who understand that results require time and strategy.",
    "whoItsFor.good.title": "Perfect Fit",
    "whoItsFor.good1": "E-shops generating €10k+ monthly revenue",
    "whoItsFor.good2": "Ready to invest minimum €1,500/month in advertising",
    "whoItsFor.good3": "Established products with strong margins",
    "whoItsFor.good4": "Seeking a long-term partner focused on results",
    "whoItsFor.bad.title": "Not a Match",
    "whoItsFor.bad1": "Early-stage startups without proven market fit",
    "whoItsFor.bad2": "Looking for overnight success or shortcuts",
    "whoItsFor.bad3": "Unwilling to invest in professional marketing",
    "whoItsFor.bad4": "Need to control every detail of execution",
    "founder.title": "Meet the Founder",
    "founder.quote": "\"I started this because I realized many e-shops lack the time for quality content and strategic marketing. I believe we can genuinely help solve that problem.\"",
    "founder.name": "Damian",
    "founder.role": "Founder, Dolphin Wave Media",
    "faq.label": "FAQ",
    "faq.title1": "Frequently",
    "faq.title2": " Asked Questions",
    "faq.q1": "What budget should I allocate for advertising?",
    "faq.a1": "We recommend minimum €1,500/month to conduct proper testing and optimization. With €3,000-10,000 monthly, we typically achieve the best results.",
    "faq.q2": "When can I expect to see results?",
    "faq.a2": "Initial results typically appear within 2-4 weeks. However, sustainable growth and complete optimization require 2-3 months of testing and refinement.",
    "faq.q3": "Which advertising platforms do you specialize in?",
    "faq.a3": "Meta (Facebook and Instagram), Google (Search, Shopping, Performance Max), and TikTok. We'll recommend the right mix based on your business.",
    "faq.q4": "Do you handle creative production?",
    "faq.a4": "Yes, absolutely. We create copy, graphics, videos, user-generated content, and optimize landing pages—the complete package.",
    "faq.q5": "How is your pricing structured?",
    "faq.a5": "Monthly retainer covering strategy, creative development, campaign management, and ongoing optimization. Pricing depends on your budget and project scope. Contact us for a personalized quote.",
    "faq.q6": "How do we stay in touch?",
    "faq.a6": "Direct communication via Slack or WhatsApp, weekly performance reports, and calls as needed to discuss strategy and results.",
    "cta.title": "Ready to grow your e-shop?",
    "cta.description": "Book a free 15-minute consultation. We'll review your current marketing and show you exactly where your growth opportunities are.",
    "cta.button": "Book Free Consultation",
    "cta.note": "No obligation",
    "footer.description": "Performance marketing for e-commerce. Meta Ads, Google Ads, TikTok Ads.",
    "footer.navigation": "Navigation",
    "footer.contact": "Contact",
    "footer.rights": "© 2026 Dolphin Wave Media. All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "leadgen.hero.headline": "More Qualified Leads.",
    "leadgen.hero.subheadline": "We help B2B and service-based companies build lead generation systems that attract, qualify, and convert.",
    "leadgen.trustmetrics.label": "Proven Track Record",
    "leadgen.trustmetrics.experience": "12+ Years Combined Experience",
    "leadgen.trustmetrics.clients": "10+ Clients Helped",
    "leadgen.trustmetrics.leads": "5,342+ Leads Generated",
    "leadgen.trustmetrics.partners": "5+ Active Partners",
    "leadgen.problems.label": "The Real Challenge",
    "leadgen.problems.headline": "This is 99% why your lead gen isn't working",
    "leadgen.problems.description": "Many businesses assume the problem is simple: they just need more ads, more traffic, or a bigger budget. But in reality, lead generation failures come from deeper systemic issues.",
    "leadgen.problem1": "The message is unclear.",
    "leadgen.problem2": "The creative does not build trust.",
    "leadgen.problem3": "The funnel leaks attention.",
    "leadgen.problem4": "The landing page does not convert.",
    "leadgen.problem5": "The offer is not positioned correctly.",
    "leadgen.problem6": "The follow-up is not strong enough.",
    "leadgen.solution": "That's why we do more than just launch campaigns. At Dolphin Wave Media, we help businesses build a lead generation system that actually works—from ads and creative to funnel design, landing pages, and overall strategy.",
    "leadgen.services.label": "What We Deliver",
    "leadgen.services.title": "Lead Generation Services Built for Results",
    "leadgen.services.meta": "Meta & Google Ads",
    "leadgen.services.meta.desc": "Strategic ad campaigns designed to attract your ideal leads on Facebook, Instagram, and Google.",
    "leadgen.services.landing": "Landing Pages",
    "leadgen.services.landing.desc": "High-converting landing pages optimized to capture leads and guide prospects through your funnel.",
    "leadgen.services.funnel": "Lead Funnels",
    "leadgen.services.funnel.desc": "End-to-end funnel architecture from awareness to lead capture, designed for your specific industry.",
    "leadgen.services.automation": "Lead Automation",
    "leadgen.services.automation.desc": "Email sequences, workflows, and CRM setup to nurture leads automatically and close more deals.",
    "leadgen.benefits.label": "Why Work With Us",
    "leadgen.benefits.title": "Quality Over Quantity",
    "leadgen.benefits.desc": "We don't just generate leads—we generate qualified leads that are ready to buy.",
    "leadgen.benefits.point1": "Strategic ad account setup and continuous optimization",
    "leadgen.benefits.point2": "Custom landing page development for maximum conversion",
    "leadgen.benefits.point3": "Lead nurturing sequences and CRM integration",
    "leadgen.benefits.point4": "Weekly performance reports and strategy adjustments",
    "leadgen.benefits.point5": "Direct communication and dedicated account support",
    "leadgen.benefits.point6": "Results-focused approach with clear KPIs",
    "leadgen.howitworks.label": "How We Scale Your Lead Generation",
    "leadgen.howitworks.title": "Our Process",
    "leadgen.howitworks.step1": "Audit & Strategy",
    "leadgen.howitworks.step1.desc": "We analyze your current marketing, identify ideal customer profiles, and build a lead generation roadmap.",
    "leadgen.howitworks.step2": "Setup & Launch",
    "leadgen.howitworks.step2.desc": "We create landing pages, set up ads, configure tracking, and prepare your CRM for lead capture.",
    "leadgen.howitworks.step3": "Optimize & Scale",
    "leadgen.howitworks.step3.desc": "We run A/B tests, optimize for quality leads, and scale campaigns that work.",
    "leadgen.whoitsfor.label": "Who We Work With",
    "leadgen.whoitsfor.title": "Perfect Fit",
    "leadgen.whoitsfor.good1": "B2B companies with proven service/product",
    "leadgen.whoitsfor.good2": "Service providers (consulting, SaaS, agencies)",
    "leadgen.whoitsfor.good3": "Ready to invest €1,500+ monthly in lead generation",
    "leadgen.whoitsfor.good4": "Seeking consistent, qualified lead flow",
    "leadgen.whoitsfor.bad": "Not a Match",
    "leadgen.whoitsfor.bad1": "Early-stage companies without offering clarity",
    "leadgen.whoitsfor.bad2": "Looking for overnight results or magic solutions",
    "leadgen.whoitsfor.bad3": "Unwilling to invest in professional marketing",
    "leadgen.whoitsfor.bad4": "Need full control over every execution detail",
    "leadgen.education.label": "Understanding Lead Generation",
    "leadgen.education.title": "Lead Generation Isn't Just About Traffic",
    "leadgen.education.desc": "Many companies struggle because they focus only on getting more eyeballs. But real lead generation is about building a system.",
    "leadgen.education.point1": "Not all traffic is equal—targeting matters",
    "leadgen.education.point2": "Creative must build trust, not just get clicks",
    "leadgen.education.point3": "Landing pages need compelling offers and clear CTAs",
    "leadgen.education.point4": "Follow-up sequence determines conversion rates",
    "leadgen.education.point5": "Tracking and measurement drive optimization",
    "leadgen.education.point6": "Scaling requires data-backed decisions",
    "advertising.label": "Why Advertising Matters",
    "advertising.headline1": "Don't Wait for Customers to Find You.",
    "advertising.headline2": "Go Where They Are.",
    "advertising.description": "If content is the engine of your brand, advertising is the fuel. Even the best website in the world won't make money if nobody sees it.",
    "advertising.benefit1.title": "Instant Visibility & Growth",
    "advertising.benefit1.description": "Organic growth takes years. Digital advertising (Meta, Google, TikTok) brings traffic and sales instantly. For e-commerce stores, paid advertising accounts for up to 47% of total sales.",
    "advertising.benefit2.title": "Precision Targeting",
    "advertising.benefit2.description": "We don't just show ads. We find your ideal customer. We target based on interests, behavior, and shopping habits. Your budget goes only where it makes sense.",
    "advertising.benefit3.title": "The Rule of Seven",
    "advertising.benefit3.description": "On average, people need 7 touchpoints with a brand before they buy. Retargeting keeps your brand top-of-mind and brings back 98% of people who didn't purchase on their first visit.",
    "advertising.benefit4.title": "Scaling Success",
    "advertising.benefit4.description": "Once we find winning creative, advertising lets us pour gasoline on the fire. From thousands to millions—just one click away.",
    "advertising.cta": "Get My Free Consultation",
    "testimonials.label": "What Our Clients Say",
    "testimonials.test1.quote": "\"A professional agency that understands e-commerce. They didn't just run ads—they thought about the whole funnel.\"",
    "testimonials.test1.name": "Robert Stefanco",
    "testimonials.test1.company": "Founder, Pénska Elegancia",
    "testimonials.test2.quote": "\"Communication is excellent. Proactive, transparent, always there when we need them. If I had an internal team, this would be it.\"",
    "testimonials.test2.name": "Matej Čašár",
    "testimonials.test2.company": "Founder, Bomba Zfava",
    "testimonials.test3.quote": "\"Creative strategy completely changed everything. Our ads finally convert. Results speak for themselves—best approach I've experienced.\"",
    "testimonials.test3.name": "Juraj Habala",
    "testimonials.test3.company": "Founder, Habala",
    "caseStudies.case1.title": "Children's Fashion",
    "caseStudies.case1.description": "Strong product. Weak system on paid ads. We built Meta Ads strategy and achieved scalable results.",
    "caseStudies.case1.investment": "Investment",
    "caseStudies.case1.revenue": "Revenue",
    "caseStudies.case1.roas": "ROAS",
    "caseStudies.case1.cpc": "Cost/Purchase",
    "caseStudies.case2.title": "Fashion E-shop",
    "caseStudies.case2.description": "Good budget. But they needed a complete system on paid ads. We built campaign and optimized for real results.",
    "caseStudies.case2.investment": "Investment",
    "caseStudies.case2.revenue": "Revenue",
    "caseStudies.case2.roas": "ROAS",
    "caseStudies.case2.channel": "Meta Ads",
    "caseStudies.case3.title": "Powersports E-shop",
    "caseStudies.case3.description": "They had ads running, but we built a system. Found winning creative and built proper conversion funnel.",
    "caseStudies.case3.investment": "Investment",
    "caseStudies.case3.revenue": "Revenue",
    "caseStudies.case3.roas": "ROAS",
    "caseStudies.case3.aov": "Avg. Order Value",
    "caseStudies.case4.title": "Growth Through Google Ads",
    "caseStudies.case4.description": "We launched and optimized search campaign for best products. Captured high-intent customers searching for their service.",
    "caseStudies.case4.investment": "Investment",
    "caseStudies.case4.revenue": "Revenue",
    "caseStudies.case4.conversions": "Conversions",
    "caseStudies.case4.roi": "ROI",
    "aiWork.label": "Our AI Work",
    "aiWork.headline": "AI content that sells",
    "aiWork.description": "Real case studies from our collaborations with local brands. When content is the engine of your business, we help you build it properly.",
    "aiWork.cta": "Book My Free Consultation",
    "whyAdvertisingNeeded.label": "Not Just Ads",
    "whyAdvertisingNeeded.headline": "You'll also need",
    "whyAdvertisingNeeded.description": "Meta advertising and AI content are our specialization. But truly sustainable growth needs the complete system. That's what we deliver.",
    "leadgen.testimonials.test1.quote": "\"Finally, an agency that understands lead generation. They didn't just run ads—they thought about the whole system.\"",
    "leadgen.testimonials.test1.name": "Robert Stefanco",
    "leadgen.testimonials.test1.company": "Founder, Pénska Elegancia",
    "leadgen.services.intro": "Build a Complete Lead Gen System",
    "leadgen.services.description": "We lead with paid traffic, but real performance comes from how the whole system works together.",
    "leadgen.services.s1.title": "Meta Ads for Lead Generation",
    "leadgen.services.s1.description": "We build, launch, and optimize Meta campaigns designed to generate quality leads, reduce wasted spend, and improve incoming inquiry quality.",
    "leadgen.services.s2.title": "Creative Strategy & Messaging",
    "leadgen.services.s2.description": "We develop better hooks, stronger messaging, clearer angles and ad concepts designed to stop attention and attract the right type of prospect.",
    "leadgen.services.s3.title": "Funnel Strategy",
    "leadgen.services.s3.description": "We help structure the journey from first click to booked call or submitted form, giving your traffic a better chance of becoming real opportunity.",
    "leadgen.services.s4.title": "Landing Page Optimization",
    "leadgen.services.s4.description": "We improve how your offer is presented, how your page builds trust, and how clearly it guides visitors to action.",
    "leadgen.services.s5.title": "Google Ads Support",
    "leadgen.services.s5.description": "For businesses needing high-intent demand, we support Google Ads strategies that capture people already searching for your service.",
    "leadgen.services.s6.title": "Overall Growth Strategy",
    "leadgen.services.s6.description": "We don't believe in random tactics. We help build a more complete marketing direction around your business, audience, and goals.",
    "leadgen.process.title": "How We Work",
    "leadgen.process.description": "Our collaboration process",
    "leadgen.process.step1.title": "Discovery Call",
    "leadgen.process.step1.description": "We start with a quick 15-minute call to understand your business, current lead gen setup, and goals.",
    "leadgen.process.step2.title": "Custom Strategy",
    "leadgen.process.step2.description": "If it's a strong fit, we prepare a custom marketing strategy in presentation format—built around your specific situation.",
    "leadgen.process.step3.title": "Implementation & Growth",
    "leadgen.process.step3.description": "After approval we implement the strategy, launch campaigns, and continuously optimize for better quality and volume of leads.",
    "leadgen.fitSection.title": "Is This For You?",
    "leadgen.fitSection.description": "We're not for everyone",
    "leadgen.fitSection.description2": "We work best with businesses ready to build a real lead generation system.",
    "leadgen.fitSection.goodFit.title": "Good Fit",
    "leadgen.fitSection.goodFit1": "Service businesses wanting more quality leads",
    "leadgen.fitSection.goodFit2": "Brands already have demand, but need better marketing execution",
    "leadgen.fitSection.goodFit3": "Businesses wanting stronger funnel, not just more traffic",
    "leadgen.fitSection.goodFit4": "Founders wanting growth partner, not generic agency",
    "leadgen.fitSection.notFit.title": "Not a Fit",
    "leadgen.fitSection.notFit1": "Businesses seeking immediate results without testing",
    "leadgen.fitSection.notFit2": "Companies without clear offer or weak service positioning",
    "leadgen.fitSection.notFit3": "Brands wanting only the cheapest possible option",
    "leadgen.fitSection.notFit4": "Businesses not ready to improve their funnel or sales process",
    "leadgen.founder.title": "Who's Behind It",
    "leadgen.founder.quote": "\"I started with paid media, but quickly realized real growth never comes from ads alone. The businesses that grow best usually have the right message, right funnel, right creative, and right system behind it all. That's why we focus on the bigger picture—not just setting up campaigns.\"",
    "leadgen.founder.name": "Damian Drahovsky",
    "leadgen.founder.role": "Founder, Dolphin Wave Media",
    "leadgen.faq.title": "You Have Questions?",
    "leadgen.faq.q1": "What happens after I book a free strategy?",
    "leadgen.faq.q2": "Is the strategy really free?",
    "leadgen.faq.q3": "Do you work only with e-commerce brands?",
    "leadgen.faq.q4": "Do you manage only Meta ads?",
    "leadgen.faq.q5": "Do you help with landing pages too?",
    "leadgen.faq.q6": "How long until I see results?",
    "leadgen.cta.title": "Ready for More Qualified Leads?",
    "leadgen.cta.description": "Free 15-minute call. We'll look at your current setup and show you where your growth opportunities are.",
    "leadgen.cta.button": "Book My Free Strategy",
  },
  sk: {
    "nav.services": "Služby",
    "nav.caseStudies": "Prípadové štúdie",
    "nav.about": "O nás",
    "nav.testimonials": "Referencie",
    "nav.faq": "FAQ",
    "nav.bookStrategy": "Bezplatná konzultácia",
    "hero.trusted": "Overené slovenskými a českými značkami",
    "hero.headline1": "Pomáhame e-shopom ",
    "hero.headline2": "predávať viac",
    "hero.headline3": " pomocou ",
    "hero.headline4": "AI obsahu",
    "hero.headline5": " a ",
    "hero.headline6": "Meta reklám",
    "hero.subheadline": "Pripravíme stratégiu na mieru, ušetríme vám hodiny práce na obsahu a všetko zrealizujeme od A po Z.",
    "hero.cta": "Chcem bezplatnú konzultáciu",
    "hero.stat1.value": "1 435 267€+",
    "hero.stat1.label": "Vygenerovaný obrat",
    "hero.stat2.value": "10 500+",
    "hero.stat2.label": "Objednávok",
    "hero.stat3.value": "20+",
    "hero.stat3.label": "Značiek sme škálovali",
    "hero.stat4.value": "12+",
    "hero.stat4.label": "Rokov skúseností v tíme",
    "hero.viewCaseStudies": "Pozrieť výsledky",
    "hero.microcopy": "15-minútový hovor. Stratégia v prezentácii. Na mieru pre vašu značku.",
    "services.label": "Čo robíme",
    "services.title1": "Všetko čo e-shopy potrebujú na ",
    "services.title2": "rast v 2026",
    "services.description": "Reklamy sú len časť skladačky. Staviame celý systém - stratégiu, kreatívu aj funnel. Všetko musí hrať dokopy.",
    "services.meta.title": "Meta Reklamy",
    "services.meta.description": "Kampane na Facebooku a Instagrame, ktoré predávajú. Nie len kliky, ale objednávky. Full-funnel od prvého kontaktu po nákup.",
    "services.google.title": "Google Reklamy",
    "services.google.description": "Search, Shopping a Performance Max kampane. Zachytávame ľudí, ktorí už aktívne hľadajú to, čo predávate.",
    "services.tiktok.title": "TikTok Reklamy",
    "services.tiktok.description": "Oslovíme mladšiu cieľovku cez pútavé videá. Kompletný manažment aj kreatívna stratégia.",
    "services.creative.title": "Kreatíva a obsah",
    "services.creative.description": "Reklamy, čo zastavia scrollovanie. UGC videá, grafiky, landing pages. O všetko sa postaráme.",
    "whyUs.label": "Prečo my",
    "whyUs.title1": "Robíme to inak",
    "whyUs.description": "Skúsenosti máme z vlastných projektov aj od klientov. Vieme, čo funguje a čo nie. Stále sa učíme a testujeme - lebo nás to baví.",
    "whyUs.point1.title": "Máme drive",
    "whyUs.point1.description": "Táto robota nás baví. Záleží nám na tom, aby sme ju robili dobre. A stále hľadáme, ako to robiť ešte lepšie.",
    "whyUs.point2.title": "Vidíme celý obraz",
    "whyUs.point2.description": "Neriešime len reklamy. Pozeráme sa na celý systém - web, ponuku, komunikáciu. Všetko musí sedieť.",
    "whyUs.point3.title": "Šetríme vám čas",
    "whyUs.point3.description": "Stratégia, obsah, realizácia - to všetko berieme na seba. Vy sa m��žete venovať biznisu.",
    "whyUs.point4.title": "Reálne výsledky",
    "whyUs.point4.description": "Zaujímajú nás čísla, ktoré majú zmysel. Predaje, obrat, rast. Nie len metriky na papieri.",
    "howItWorks.label": "Ako to funguje",
    "howItWorks.title1": "Škálujeme značky v ",
    "howItWorks.title2": "90-dňovom teste",
    "howItWorks.step1.title": "Analýza",
    "howItWorks.step1.description": "Pozrieme sa na váš marketing, konkurenciu a príležitosti. Pripravíme plán rastu.",
    "howItWorks.step2.title": "Stratégia a kreatíva",
    "howItWorks.step2.description": "Navrhneme reklamnú stratégiu, vytvoríme kreatívy a nastavíme meranie.",
    "howItWorks.step3.title": "Spustenie a optimalizácia",
    "howItWorks.step3.description": "Kampane bežia. Denne sledujeme výkon a ladíme pre maximálny ROAS.",
    "howItWorks.step4.title": "Škálovanie",
    "howItWorks.step4.description": "Keď nájdeme víťazné kombinácie, ideme do objemu. S rozumom a profitom.",
    "howItWorks.cta": "Poďme na to",
    "howItWorks.note": "Prvá spolupráca: 90 dní. Potom dlhodobé partnerstvo postavené na výsledkoch.",
    "caseStudies.label": "Výsledky",
    "caseStudies.title1": "Reálne čísla,",
    "caseStudies.title2": " reálne značky",
    "caseStudies.description": "Pozrite sa, ako sme pomohli e-shopom rásť cez platenej reklamy.",
    "testimonials.quote": "\"Vidím, že do toho dávate effort a že vám na tom naozaj záleží. To ma teší. Zatiaľ najlepší prístup k reklamám, aký som zažil.\"",
    "whoItsFor.label": "Pre koho to je",
    "whoItsFor.title1": "Nie sme ",
    "whoItsFor.title2": "pre každého",
    "whoItsFor.description": "Spolupracujeme so značkami, ktoré sú pripravené investovať do rastu. A chápu, že výsledky chcú čas.",
    "whoItsFor.good.title": "Sedíme si",
    "whoItsFor.good1": "E-shopy s obratom 10 000€+ mesačne",
    "whoItsFor.good2": "Pripravení investovať min. 1 500€/mesiac do reklám",
    "whoItsFor.good3": "Overený produkt s dobrými maržami",
    "whoItsFor.good4": "Hľadáte partnera na dlhšie, nie rýchle fixky",
    "whoItsFor.bad.title": "Nesedíme si",
    "whoItsFor.bad1": "Startupy bez overeného produktu",
    "whoItsFor.bad2": "Chcete úspech cez noc alebo nejaké hacky",
    "whoItsFor.bad3": "Nechcete investovať do poriadneho marketingu",
    "whoItsFor.bad4": "Potrebujete kontrolovať každý detail",
    "founder.title": "Kto za tým stojí",
    "founder.quote": "\"Začal som s tým, lebo som videl, že veľa e-shopov proste nemá čas na obsah a správny marketing. Verím, že s tým vieme naozaj pomôcť.\"",
    "founder.name": "Damian",
    "founder.role": "Zakladateľ, Dolphin Wave Media",
    "faq.label": "FAQ",
    "faq.title1": "Časté",
    "faq.title2": " otázky",
    "faq.q1": "Koľko potrebujem na reklamy na štart?",
    "faq.a1": "Odporúčame minimálne 1 500€/mesiac, aby sme mohli poriadne testovať. S 3 000 - 10 000€ mesačne vidíme najlepšie výsledky.",
    "faq.q2": "Kedy uvidím výsledky?",
    "faq.a2": "Prvé výsledky väčšinou do 2-4 týždňov. Ale reálny, udržateľný rast chce 2-3 mesiace - kým otestujeme, čo funguje.",
    "faq.q3": "Na akých platformách robíte?",
    "faq.a3": "Meta (Facebook, Instagram), Google (Search, Shopping, Performance Max) a TikTok. Poradíme, čo dáva zmysel pre vás.",
    "faq.q4": "Robíte aj kreatívu?",
    "faq.a4": "Jasné! Texty, grafiky, videá, UGC - všetko. Aj landing pages vieme optimalizovať.",
    "faq.q5": "Ako funguje cenník?",
    "faq.a5": "Mesačný retainer - stratégia, kreatíva, manažment kampaní, optimalizácia. Cena závisí od rozpočtu a rozsahu. Zavolajte si a dáme ponuku.",
    "faq.q6": "Ako komunikujeme?",
    "faq.a6": "Priamo cez Slack alebo WhatsApp. Týždenné reporty. Keď treba, zavoláme.",
    "cta.title": "Pripravení škálovať váš e-shop?",
    "cta.description": "Bezplatná 15-minútová konzultácia. Pozrieme sa na váš marketing a ukážeme, kde je priestor na rast.",
    "cta.button": "Chcem bezplatnú konzultáciu",
    "cta.note": "Bez záväzkov",
    "footer.description": "Performance marketing pre e-shopy. Meta Ads, Google Ads, TikTok Ads.",
    "footer.navigation": "Navigácia",
    "footer.contact": "Kontakt",
    "footer.rights": "© 2026 Dolphin Wave Media. Všetky práva vyhradené.",
    "footer.privacy": "Ochrana súkromia",
    "footer.terms": "Obchodné podmienky",
    "advertising.label": "Prečo reklama",
    "advertising.headline1": "Nečakajte, kým vás zákazníci nájdu.",
    "advertising.headline2": "Choďte za nimi.",
    "advertising.description": "Ak je obsah motor vašej značky, reklama je palivo. Aj ten najlepší web na svete nezarobí, keď ho nikto nevidí.",
    "advertising.benefit1.title": "Okamžitá viditeľnosť a rast",
    "advertising.benefit1.description": "Organický rast trvá roky. Digitálna reklama (Meta, Google, TikTok) vám prinesie traffic a predaje hneď. Pre e-shopy platené reklamy tvoria až 47% celkových predajov.",
    "advertising.benefit2.title": "Presné cielenie",
    "advertising.benefit2.description": "Nerobíme len \"reklamy\". Hľadáme vášho ideálneho zákazníka. Cielime podľa záujmov, správania, nákupných zvykov. Rozpočet ide len tam, kde má zmysel.",
    "advertising.benefit3.title": "Pravidlo siedmich",
    "advertising.benefit3.description": "Človek potrebuje v priemere 7 kontaktov so značkou, kým nakúpi. Retargeting drží vašu značku v hlave a vracia 98% ľudí, čo nekúpili na prvýkrát.",
    "advertising.benefit4.title": "Škálovanie úspechu",
    "advertising.benefit4.description": "Keď nájdeme víťaznú kreatívu, reklamy nám umožňujú \"liať benzín do ohňa\". Z tisícov na milióny - stačí kliknutie.",
    "advertising.cta": "Chcem bezplatnú konzultáciu",
    "testimonials.label": "Čo hovoria naši klienti",
    "testimonials.test1.quote": "\"Profesionálna agentúra, čo rozumie e-commerce. Nespúšťali len reklamy - rozmýšľali o celom funnele.\"",
    "testimonials.test1.name": "Robert Stefanco",
    "testimonials.test1.company": "Zakladateľ, Pénska Elegancia",
    "testimonials.test2.quote": "\"Komunikácia je super. Proaktívni, transparentní, vždy tu keď ich potrebujem. Keby som mal interný tím, bol by to toto.\"",
    "testimonials.test2.name": "Matej Čašár",
    "testimonials.test2.company": "Zakladateľ, Bomba Zfava",
    "testimonials.test3.quote": "\"Kreatívna stratégia nám zmenila všetko. Naše reklamy konečne fungujú. Výsledky hovoria sami za seba - najlepší prístup, aký som zažil.\"",
    "testimonials.test3.name": "Juraj Habala",
    "testimonials.test3.company": "Zakladateľ, Habala",
    "caseStudies.case1.title": "Detská móda",
    "caseStudies.case1.description": "Silný produkt. Slabý systém na platenej reklame. Postavili sme Meta Ads stratégiu a dosiahli škálovateľné výsledky.",
    "caseStudies.case1.investment": "Investícia",
    "caseStudies.case1.revenue": "Obrat",
    "caseStudies.case1.roas": "ROAS",
    "caseStudies.case1.cpc": "Cena/nákup",
    "caseStudies.case2.title": "Módny e-shop",
    "caseStudies.case2.description": "Dobrý rozpočet. Ale potreboval kompletný systém na reklame. Postavili sme kampane a prevádzali ich na reálne výsledky.",
    "caseStudies.case2.investment": "Investícia",
    "caseStudies.case2.revenue": "Obrat",
    "caseStudies.case2.roas": "ROAS",
    "caseStudies.case2.channel": "Meta Ads",
    "caseStudies.case3.title": "Powersports e-shop",
    "caseStudies.case3.description": "Mali reklamy, ale my sme postavili systém. Našli vyhrávajúcu kreatívu a postavili funnel na konverziu.",
    "caseStudies.case3.investment": "Investícia",
    "caseStudies.case3.revenue": "Obrat",
    "caseStudies.case3.roas": "ROAS",
    "caseStudies.case3.aov": "Priem. obj.",
    "caseStudies.case4.title": "Rast cez Google Ads",
    "caseStudies.case4.description": "Spustili a optimalizovali sme search kampane na najlepšie produkty. Zachytávali sme ľudí s vysokým zámerom.",
    "caseStudies.case4.investment": "Investícia",
    "caseStudies.case4.revenue": "Obrat",
    "caseStudies.case4.conversions": "Konverzie",
    "caseStudies.case4.roi": "Návrátnosť",
    "aiWork.label": "Naša AI práca",
    "aiWork.headline": "AI obsah, ktorý predáva",
    "aiWork.description": "Reálne príklady zo spolupráce s lokálnymi značkami. Keď je obsah motorom vášho biznisu, pomáhame vám ho stavať poriadne.",
    "aiWork.cta": "Chcem bezplatnú konzultáciu",
    "whyAdvertisingNeeded.label": "Nielen reklamy",
    "whyAdvertisingNeeded.headline": "Toto budete tiež potrebovať",
    "whyAdvertisingNeeded.description": "Meta reklamy a AI obsah sú naša špecializácia. Ale skutočný, udržateľný rast potrebuje kompletný systém. To je to, čo dodávame.",
    "leadgen.testimonials.test1.quote": "\"Konečne agentúra, čo rozumie lead gen. Nespúšťali len reklamy - rozmýšľali o celom systéme.\"",
    "leadgen.testimonials.test1.name": "Robert Stefanco",
    "leadgen.testimonials.test1.company": "Zakladateľ, Pénska Elegancia",
    "leadgen.services.intro": "Postavte kompletný lead gen systém",
    "leadgen.services.description": "Vedieme to cez platený traffic, ale skutočný výkon pochádza z toho, ako celý systém funguje spolu.",
    "leadgen.services.s1.title": "Meta Ads pre generovanie leadov",
    "leadgen.services.s1.description": "Staviame, spúšťame a optimalizujeme Meta kampane navrhnuté na generovanie kvalitných leadov, zníženie zbytočných výdavkov a zlepšenie kvality prichádzajúcich dopytov.",
    "leadgen.services.s2.title": "Kreatívna stratégia a messaging",
    "leadgen.services.s2.description": "Vyvíjame lepšie hooky, silnejšie správy, jasnejšie uhly a koncepty reklám vytvorené tak, aby zastavili pozornosť a pritiahli správny typ záujemcu.",
    "leadgen.services.s3.title": "Stratégia funnelu",
    "leadgen.services.s3.description": "Pomáhame štruktúrovať cestu od prvého kliknutia po zarezervovaný hovor alebo odoslaný formulár, aby váš traffic mal lepšiu šancu stať sa reálnou príležitosťou.",
    "leadgen.services.s4.title": "Optimalizácia landing pages",
    "leadgen.services.s4.description": "Vylepšujeme spôsob, akým je vaša ponuka prezentovaná, ako vaša stránka komunikuje dôveru a ako jasne vedie návštevníkov k akcii.",
    "leadgen.services.s5.title": "Podpora Google Ads",
    "leadgen.services.s5.description": "Pre biznisy, ktoré potrebujú dopyt s vysokým zámerom, podporujeme Google Ads stratégie, ktoré zachytávajú ľudí už hľadajúcich vašu službu.",
    "leadgen.services.s6.title": "Celková rastová stratégia",
    "leadgen.services.s6.description": "Neveríme v náhodné taktiky. Pomáhame budovať kompletnejší marketingový smer okolo vášho biznisu, publika a cieľov.",
    "leadgen.process.title": "Náš proces",
    "leadgen.process.description": "Ako spolupracujeme",
    "leadgen.process.step1.title": "Discovery hovor",
    "leadgen.process.step1.description": "Začíname krátkym 15-minútovým hovorom, aby sme pochopili váš biznis, aktuálne nastavenie generovania leadov a vaše ciele.",
    "leadgen.process.step2.title": "Stratégia na mieru",
    "leadgen.process.step2.description": "Ak je tu silný fit, pripravíme marketingovú stratégiu na mieru v prezentačnom formáte - postavenú okolo vašej konkrétnej situácie.",
    "leadgen.process.step3.title": "Realizácia a rast",
    "leadgen.process.step3.description": "Po schválení realizujeme stratégiu, spúšťame kampane a neustále optimalizujeme pre lepšiu kvalitu a objem leadov.",
    "leadgen.fitSection.title": "Je to pre vás?",
    "leadgen.fitSection.description": "Nie sme pre každého",
    "leadgen.fitSection.description2": "Najlepšie spolupracujeme s biznismi, ktoré sú pripravené budovať reálny systém generovania leadov.",
    "leadgen.fitSection.goodFit.title": "Sedíme si",
    "leadgen.fitSection.goodFit1": "Servisné biznisy, ktoré chcú viac kvalitných leadov",
    "leadgen.fitSection.goodFit2": "Značky, ktoré už majú dopyt, ale potrebujú lepšiu marketingovú realizáciu",
    "leadgen.fitSection.goodFit3": "Biznisy, ktoré chcú silnejší funnel, nie len viac trafficu",
    "leadgen.fitSection.goodFit4": "Zakladatelia, ktorí chcú rastového partnera, nie generickú agentúru",
    "leadgen.fitSection.notFit.title": "Nesedíme si",
    "leadgen.fitSection.notFit1": "Biznisy hľadajúce okamžité výsledky bez testovania",
    "leadgen.fitSection.notFit2": "Firmy bez jasnej ponuky alebo slabého pozicionovania služby",
    "leadgen.fitSection.notFit3": "Značky, ktoré chcú len najlacnejšiu možnú možnosť",
    "leadgen.fitSection.notFit4": "Biznisy, ktoré nie sú pripravené zlepšiť svoj funnel alebo predajný proces",
    "leadgen.founder.title": "Kto za tým stojí",
    "leadgen.founder.quote": "\"Začal som s plateným médiom, ale rýchlo som si uvedomil, že skutočný rast nikdy nepochádza len z reklám. Biznisy, ktoré rastú najlepšie, majú zvyčajne správnu správu, správny funnel, správnu kreatívu a správny systém za tým všetkým. Preto sa zameriavame na väčší obraz - nie len na nastavenie kampaní.\"",
    "leadgen.founder.name": "Damian Drahovsky",
    "leadgen.founder.role": "Zakladateľ, Dolphin Wave Media",
    "leadgen.faq.title": "Máte otázky?",
    "leadgen.faq.q1": "Čo sa stane po tom, čo si rezervujem bezplatnú stratégiu?",
    "leadgen.faq.q2": "Je stratégia naozaj zadarmo?",
    "leadgen.faq.q3": "Pracujete len s e-commerce značkami?",
    "leadgen.faq.q4": "Spravujete len Meta reklamy?",
    "leadgen.faq.q5": "Pomáhate aj s landing pages?",
    "leadgen.faq.q6": "Ako dlho trvá, kým uvidím výsledky?",
    "leadgen.cta.title": "Pripravení získať viac kvalitných leadov?",
    "leadgen.cta.description": "Bezplatný 15-minútový hovor. Pozrieme sa na vaše aktuálne nastavenie a ukážeme vám, kde je priestor na rast.",
    "leadgen.cta.button": "Chcem bezplatnú stratégiu",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Always default to 'sk' (Slovak) - no hydration mismatches
  const [language, setLanguage] = useState<Language>('sk')

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
